---
- name: When Testing
  hosts: local
  vars:
    my_str: whatever
    version: "Cisco IOS running version 15.2"

  tasks:
    - name: Testing string equality
      debug:
        msg: whatever
      when: my_str != 'whatever'

    - name: Substring in larger string
      debug:
        msg: This is Cisco IOS
      when: "'Cisco IOS' in version"

    - name: This variable is defined
      debug:
        msg: Variable defined
      when: version is defined
