
---
- name: EOS Example
  hosts: arista
  vars:
    eapi:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: eapi
      use_ssl: True
      validate_certs: no

  tasks:
    - name: Execute Show Command
      eos_command:
        provider: "{{ eapi }}"
        commands: show arp
